In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
#Saving an array

np.save('myarray', arr)

In [6]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [11]:
#Save multiple arrays

arr1 = np.load('myarray.npy')
arr2 = arr

arr1

array([0, 1, 2, 3, 4])

In [12]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#Saving as zip

np.savez('twoarrays.npz', x=arr1, y=arr2)

In [20]:
newArray = np.load('twoarrays.npz')

In [21]:
newArray['x']

array([0, 1, 2, 3, 4])

In [22]:
newArray['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#save in different format

arr = np.array([[1,2,3], [4,5,6]])

np.savetxt('txtarray.txt', arr, delimiter=',')


In [30]:
arr = np.loadtxt('txtarray.txt', delimiter=',')

arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])