In [1]:
import numpy as np

In [3]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)

A

array([ 0.26116449,  0.43961955, -0.74866086,  0.32239293,  0.38346426,
        0.24523146,  1.02478261, -0.5297037 ,  0.14197891, -0.51332103])

In [9]:
B = np.random.randn(10)

B

array([ 2.61537872, -0.83303734,  0.30703421, -2.03221245,  0.50043934,
        0.47247752, -0.29898341,  0.6300787 ,  0.91564379,  0.87420101])

In [10]:
#Binary Functions

np.add(A, B)

array([ 2.87654321, -0.39341779, -0.44162665, -1.70981952,  0.8839036 ,
        0.71770898,  0.7257992 ,  0.100375  ,  1.05762271,  0.36087998])

In [12]:
np.maximum(A, B)

array([ 2.61537872,  0.43961955,  0.30703421,  0.32239293,  0.50043934,
        0.47247752,  1.02478261,  0.6300787 ,  0.91564379,  0.87420101])

In [13]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True